openapi: 3.0.1

info:
  title: Hacker News
  version: 1.0.0
  description: "This is the Open API documentation for the REST API of our beloved application **Hacker News** deployed at <'nomServer'/>. <br>All operations are executable."

  servers:
    - url: #to be determined

  paths: